### ISSUE TITLE
LV-909 "Terrier" Liquid Fuel Engine - Small hole on inside of engine bell at throat of 1.25m variant

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#291]
The engine bell of the 3 variant models is conical and goes to a single vertice point. On the Boattail and Compact variant this looks nominal but on the 1.25m variant, the shroud that blocks off the internals cuts through the throat of the bell causing the engine bell to have a small part of this face visible on the far inside of the bell, near the throat. It looks a little odd as this face is coloured bright grey.

See the Boattail variant looking nominal:

![untitled-1](https://user-images.githubusercontent.com/10106634/52179015-052b1800-27cd-11e9-8626-cb149f9c7b34.png)

See the 1.25m variant with the small, light grey, circle at the bottom:

![untitled-2](https://user-images.githubusercontent.com/10106634/52179018-1116da00-27cd-11e9-9490-3129b5f3ac5c.png)

Here is a close up where you can see the inside of the bell 'cone' being truncated by this light, grey face:

![untitled-3](https://user-images.githubusercontent.com/10106634/52179023-1f64f600-27cd-11e9-94ba-c7448fa9f140.png)

**Comment by ChrisAdderley** [comment]
Addressed in 0d79074

**Comment by Poodmund** [comment]
@ChrisAdderley 	it doesn't seem as though the Terrier's new .mu was uploaded in the https://github.com/PorktoberRevolution/ReStocked/commit/0d790746cbc65048e7b8cb70d0697aa305253736 commit.

Using the latest master build https://github.com/PorktoberRevolution/ReStocked/commit/a55c6a48f0dfbdf512bbc36a5a5711597b790904 I still see the issue described above.

**Comment by ChrisAdderley** [comment]
763a495 looks fine to me, if you see something more, it's too minor.

**Comment by Poodmund** [comment]
Its now resolved. 😄
