### ISSUE TITLE
Launch Escape System - Seam in model

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#697]
There seems to be a mesh seam as the front of the part that runs down the entire front face of the part. You can see the thin black seam in the screenshots below:

![Untitled-1](https://user-images.githubusercontent.com/10106634/67622588-71462400-f813-11e9-81f8-247787bdb41b.png)

**Comment by drewcassidy** [comment]
Hopefully addressed in b17eb79f60a7376041b5a29185cb3683d1809774

**Comment by Poodmund** [comment]
Unfortunately the same issue seems to be persisting with b17eb79

**Comment by drewcassidy** [comment]
I’m not sure what to do about it then, I don’t see a seam in Unity

**Comment by drewcassidy** [comment]
Try again with 5b8395824e916b56d409a81de0e780e88566b24c

**Comment by Poodmund** [comment]
Unfortunately its still occurring, primarily, on the side thats opposite the top thruster and to a lesser extent the side to the left of the top thruster.

![Untitled-1](https://user-images.githubusercontent.com/10106634/67680300-e2f0b000-f982-11e9-9e3b-1a5bdb611c4d.png)

![Untitled-2](https://user-images.githubusercontent.com/10106634/67680465-3236e080-f983-11e9-8d3e-3410e7025658.png)

**Comment by Poodmund** [comment]
Could be resolved using the same method as https://github.com/PorktoberRevolution/ReStocked/issues/815.

> IIRC he fixed it by making the inside mesh of the shell a separate object. try that?
> Cos it doesn't ever seem to occur on regular thick manifold stuff with no insides
> Like, why does seperating the mesh even fix it
> ok, it gets weirder
> just for fun, i reattached the mesh
> it's still gone!
> so... detach inside, reattach, profit?
