### ISSUE TITLE
Landing Legs - Somehow weaker than stock

### ISSUE THREAD

**Issue by drewcassidy** [PorktoberRevolution/ReStocked#858]
**Describe the bug**
the landing legs break more easily with restock installed

**List of mods installed:**
 - Restock

**Comment by drewcassidy** [comment]
After many hours of frustration, I've come to the conclusion that the stock wheel module is just wildly inconsistent. I was able to get the restock version of the legs to survive a long drop like their stock counterparts did consistently, but only some of the time. Whether the legs survived or exploded seemed to correspond with how long after scene-change I did the drop? 

I've pushed a refactored version of the .mu file to the master branch which should hopefully more closely match stock, but I'm at a complete loss as to how to fully solve this issue

**Comment by drewcassidy** [comment]
...I may have read the original report wrong but I definitely was able to reproduce with the LT-1

**Comment by JonnyOThan** [comment]
I got a report that this is still happening on the LT-2.  The commit that addressed this only changed the LT-1: https://github.com/PorktoberRevolution/ReStocked/pull/863/commits/58d30d084bc6de3b10f661f357e5b222f0448eb8

**Comment by sug44** [comment]
Just fixed the LT-2 legs(https://github.com/PorktoberRevolution/ReStocked/pull/1007) the same way LT-1 legs were fixed in https://github.com/PorktoberRevolution/ReStocked/commit/58d30d084bc6de3b10f661f357e5b222f0448eb8. What mine and https://github.com/PorktoberRevolution/ReStocked/commit/58d30d084bc6de3b10f661f357e5b222f0448eb8 fix did was change the model hierarchy so that collider collections are not inside of wrapper objects and set object names to the same ones used in the stock leg. If you only change the hierarchy legs become rigid and if you only change the names legs stay weak, so it only works if you do both, although im probably missing something. Note that LT-5(the smallest legs) have the same issue, but I couldn't fix it since the hierarchy differs a lot from the stock one, but its possible if you know how to do ksp modeling.

**Comment by Poodmund** [comment]
Is this the cause for the LT-2 and LT-5 as shown here: https://github.com/PorktoberRevolution/ReStocked/issues/1003#issuecomment-2135956996 ?

**Comment by sug44** [comment]
If the vibration issue only happens to lt-2 and lt-5 but not to lt-1 legs then its most likely related to this issue. But I can only guess since I have no idea what causes this bug. You could check if the vibration issue presists on lt-2 legs after the #1007 fix to know for sure
